### ISSUE TITLE
Put all the static import at the beginning or at the end of the import list

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1439]
See #1434

**Comment by pvojtechovsky** [comment]
I guess this was already fixed by TokenWriter feature or #1434. It can be probably closed

**Comment by surli** [comment]
#1434 did not solve that one. However I don't know if TokenWriter feature change something about that. At least, we should keep it and add a test.

**Comment by pvojtechovsky** [comment]
During refactorings needed by TokenWriter I touched also printing of imports. And I added there such kind of sorting. So just test is probably missing ...
