### ISSUE TITLE
chore: revapi script seems broken

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1694]
Show no changes even if there is changes. Seems related to #1683

**Comment by monperrus** [comment]
a regexp was broken due to the template change.
fixed it in Gakoci job `pull_request-INRIA-spoon-api-revapi`

**Comment by surli** [comment]
It's still broken, but with an error in gakoci apparently: 

> File "./gakoci/gakoci.py", line 140, in set_commit_status
    assert resp.status_code == 201, (resp.status_code, resp.text)
AssertionError: (401, '{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}')

**Comment by monperrus** [comment]
I burned the previous gakoci auth token by publishing it to Github. 
Just recreated one with spoon-bot, and it works again
