### ISSUE TITLE
Spoon generate duplicate brackets in invocations.

### ISSUE THREAD

**Issue by nemo9cby** [INRIA/spoon#2330]
After applying processing, there will be duplicate brackets inside invocations if they contain "+".

For example, if the original line is like:
`logger.info("Value declared in if:" + c);`

After parsing in Spoon, it would become:
`logger.info(("Value declared in if:" + c));`

Another example:
before:
`LOG.warn("AuthenticationToken ignored: " + ex.getMessage());`
after:
`LOG.warn(("AuthenticationToken ignored: " + (ex.getMessage())));`

The processor looks like:
```
public class CusProcessor extends AbstractProcessor<CtStatement> {
    public void process(CtStatement element) {
        if (element instanceof CtInvocationImpl) {
            CtInvocationImpl invoke = (CtInvocationImpl) element;
            System.out.println(invoke);
        }
    }
}
```

Launcher code:
```
        Launcher launcher = new Launcher();
        launcher.addInputResource(filePath);
        launcher.getEnvironment().setNoClasspath(true); 
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setOutputType(OutputType.NO_OUTPUT);
        launcher.getEnvironment().setCommentEnabled(false);
        launcher.addProcessor(new CusProcessor());
        launcher.run();
```
My guess is that it is because of the internal compiler, is there a way to fix this?

**Comment by surli** [comment]
Hi @nemo9cby thanks for reporting this one!
It was already reported by @pvojtechovsky and it should have been fixed with #2113. So you might want to try the latest snapshot of Spoon to check if it solve your problem: it will be integrated in the next release.

**Comment by nemo9cby** [comment]
Hi @surli , thanks for the reply!
I am currently using 7.0.0 and it shows in the change log that the bug #2113 has been fixed in this snapshot. So by saying "next release" do you mean that 7.0.0 is not able to deal with this issue and we need to build the snapshot using the latest commit?

**Comment by nemo9cby** [comment]
Actually I just checked version 7.0.0, it already contains the code changes of #2113. This issue still exists.

**Comment by surli** [comment]
My bad then: I though #2113 was not yet integrated in a Spoon release. So yeah it's a new bug.

**Comment by Egor18** [comment]
Resolved by #3024
